interface BgImageProps {
  /** srcset string generated by vite-imagetools (e.g. import img from "...?w=640;1024;1600&format=webp&as=srcset") */
  srcSet: string;
  /** fallback src (largest variant or original) */
  src: string;
  alt?: string;
  className?: string;
  eager?: boolean;
}

/**
 * Full-bleed background image that adapts to the device.
 * The browser picks the smallest variant that fits the viewport (via srcset),
 * so phones download a small image, desktops a large one — fast everywhere.
 */
export const BgImage = ({
  srcSet,
  src,
  alt = "",
  className = "",
  eager = false,
}: BgImageProps) => (
  <img
    src={src}
    srcSet={srcSet}
    sizes="100vw"
    alt={alt}
    className={`w-full h-full object-contain object-center sm:object-cover ${className}`}
    loading={eager ? "eager" : "lazy"}
    fetchPriority={eager ? "high" : "auto"}
    decoding="async"
  />
);
