// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvlhbcovguyiihbojcyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bGhiY292Z3V5aWloYm9qY3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MjU1ODUsImV4cCI6MjA4NjIwMTU4NX0.5bEZUlZZ2xDKc46OEKqrg-U3RnOgIDNT5NAZF1YD46c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});